trigger: none

variables:
- group: one2onetool-var
- name: branchname
  value: 'staging'

stages:
- stage: Build
  displayName: Build Docker Image and Push to ECR
  jobs:
  - job: Build_Release
    displayName: Build Release
    pool: one2onetool
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'

    - task: DockerInstaller@0
      inputs:
        dockerVersion: '17.09.0-ce'
      displayName: 'Install Docker'

    - script: |
        npm ci
        npm test
      displayName: 'npm ci and npm test'
      workingDirectory: '$(Build.SourcesDirectory)'

    - script: |
        sed -i 's/DATA_FILE=""/DATA_FILE='$(datafile-release)'/' Dockerfile
        cat ./Dockerfile
      displayName: 'Update Dockerfile'
      workingDirectory: '$(Build.SourcesDirectory)'

    - script: |
        docker build -t $(image-name):$(branchname).$(Build.BuildId) .
      displayName: 'docker build'
      workingDirectory: '$(Build.SourcesDirectory)'

    - script: |
        docker tag $(image-name):$(branchname).$(Build.BuildId) $(repo-domain)/$(image-name):$(branchname).$(Build.BuildId)
        docker push $(repo-domain)/$(image-name):$(branchname).$(Build.BuildId)
      displayName: 'Push Image to ECR'
      workingDirectory: '$(Build.SourcesDirectory)'